apiVersion: batch/v1
kind: CronJob
metadata:
  name: ip-updater
spec:
  schedule: "0 */2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 7200 # keep one job
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: backup
            image: ip-updater:0.2.0
            volumeMounts:
            - mountPath: /etc/ip-updater.yaml
              subPath: ip-updater.yaml
              name: config
          volumes:
          - name: config
            secret:
              secretName: ip-updater
